import { zodResolver } from '@hookform/resolvers/zod';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { CheckCircle2, UserPlus } from 'lucide-react';
import { useForm } from 'react-hook-form';
import { Link, useSearchParams } from 'react-router-dom';
import { z } from 'zod';
import { api, apiMessage } from '../services/api.js';
import { mobileErrorMessage, mobilePattern, sanitizeMobileEvent } from '../utils/validation.js';

const password=z.string().min(10,'Use at least 10 characters').regex(/[A-Z]/,'Include an uppercase letter').regex(/[a-z]/,'Include a lowercase letter').regex(/\d/,'Include a number');
const schema=z.object({fullName:z.string().min(2),mobile:z.string().regex(mobilePattern,mobileErrorMessage),email:z.string().email().or(z.literal('')),password,city:z.string().min(2),state:z.string().min(2),businessName:z.string().optional(),referredByCode:z.string().max(40).optional(),consent:z.literal(true,{errorMap:()=>({message:'Consent is required'})})});
export function AccountRegisterPage({accountType}){const [params]=useSearchParams();const queryClient=useQueryClient();const form=useForm({resolver:zodResolver(schema),defaultValues:{fullName:'',mobile:'',email:'',password:'',city:'',state:'',businessName:'',referredByCode:params.get('ref')||'',consent:false}});const register=useMutation({mutationFn:async(values)=>(await api.post(`/auth/${accountType}/register`,values)).data.data,onSuccess:({user})=>queryClient.setQueryData(['session'],user)});const dashboard=`/${accountType}/dashboard`;if(register.isSuccess)return <section className="page-hero"><div className="shell narrow success-panel"><CheckCircle2/><span className="eyebrow">Account created</span><h1>Welcome, {register.data.user.fullName}.</h1><p>Your permanent referral code is <strong>{register.data.user.referralCode}</strong>. Registration created a real MongoDB profile and secure session.</p><Link className="button button-gold" to={dashboard}>Open dashboard</Link></div></section>;return <section className="auth-section"><div className="auth-aside"><UserPlus/><span className="eyebrow">{accountType} registration</span><h1>Create your secure {accountType} account.</h1><p>A permanent unique referral code is generated automatically. An optional valid referred-by code connects the registration to its owner.</p></div><form className="form-card auth-form" onSubmit={form.handleSubmit((values)=>register.mutate(values))} noValidate><h2>Create {accountType} account</h2><div className="form-grid"><Field label="Full name" name="fullName" form={form}/><Field label="Mobile number" name="mobile" type="tel" form={form}/><Field label="Email (optional)" name="email" type="email" form={form}/>{accountType==='contractor'&&<Field label="Business / agency (optional)" name="businessName" form={form}/>}<Field label="City" name="city" form={form}/><Field label="State" name="state" form={form}/></div><Field label="Password" name="password" type="password" form={form}/><Field label="Referred by code (optional)" name="referredByCode" form={form} readOnly={Boolean(params.get('ref'))}/><label className="checkbox"><input type="checkbox" {...form.register('consent')}/><span>I accept the privacy notice and consent to creation of this account.</span></label>{form.formState.errors.consent&&<small className="field-error" role="alert">{form.formState.errors.consent.message}</small>}<button className="button button-gold" disabled={register.isPending}>{register.isPending?'Creating account…':'Create secure account'}</button>{register.isError&&<p className="form-error" role="alert">{apiMessage(register.error)}</p>}<p>Already registered? <Link to={`/${accountType}/sign-in`}>Sign in</Link></p></form></section>}
function Field({label,name,type='text',form,readOnly=false}){const error=form.formState.errors[name];return <label>{label}<input type={type} inputMode={type==='tel'?'tel':undefined} readOnly={readOnly} aria-invalid={Boolean(error)} onInput={type==='tel'?sanitizeMobileEvent:undefined} {...form.register(name)}/>{error&&<small className="field-error" role="alert">{error.message}</small>}</label>}
