import { useMutation, useQuery } from '@tanstack/react-query';
import { ArrowLeft, ArrowRight, CheckCircle2, FileLock2, Save } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useForm } from 'react-hook-form';
import { Link, useSearchParams } from 'react-router-dom';
import { Breadcrumbs } from '../components/Breadcrumbs.jsx';
import { Seo } from '../components/Seo.jsx';
import { api, apiMessage } from '../services/api.js';
import { trackEvent } from '../services/analytics.js';
import { mobileErrorMessage, mobilePattern, sanitizeMobile, sanitizeMobileEvent } from '../utils/validation.js';

const steps=['Service','Personal','Financial','Requirement','Documents','Consent'];
const fieldsByStep=[['service'],['personal.fullName','personal.mobile','personal.email','personal.dateOfBirth','personal.city','personal.state','personal.pinCode'],['financial.employmentType','financial.requestedAmount'],['serviceSpecific.requirementSummary','referralCode'],[],['consents.privacy','consents.accuracy','consents.terms']];
const draftStorageKey='vfs_application_draft';
const defaults={service:'',personal:{fullName:'',mobile:'',email:'',dateOfBirth:'',city:'',state:'',pinCode:''},financial:{employmentType:'salaried',employerOrBusinessName:'',monthlyIncome:0,annualTurnover:0,existingEmi:0,requestedAmount:0,itrStatus:'not_sure',creditProfile:'not_sure'},serviceSpecific:{requirementSummary:''},referralCode:'',consents:{privacy:false,communication:false,accuracy:false,terms:false},website:''};
function storedDraft(){try{return JSON.parse(localStorage.getItem(draftStorageKey))||null}catch{return null}}

export function ApplyPage(){
  const [params]=useSearchParams(); const [step,setStep]=useState(0); const [draftSession,setDraftSession]=useState(storedDraft); const [draftMessage,setDraftMessage]=useState('');
  const services=useQuery({queryKey:['services'],queryFn:async()=>(await api.get('/services')).data.data});
  const form=useForm({defaultValues:{...defaults,referralCode:params.get('ref')||''}});
  const savedDraft=useQuery({queryKey:['application-draft',draftSession?.draftId],enabled:Boolean(draftSession?.draftId&&draftSession?.resumeToken),queryFn:async()=>(await api.get(`/applications/public/drafts/${draftSession.draftId}`,{headers:{'x-resume-token':draftSession.resumeToken}})).data.data,retry:false});
  useEffect(()=>{const slug=params.get('service');const item=services.data?.find((entry)=>entry.slug===slug);if(item&&!draftSession)form.setValue('service',item._id)},[params,services.data,form,draftSession]);
  useEffect(()=>{if(!savedDraft.data)return;const data=savedDraft.data;form.reset({...defaults,...data,personal:{...defaults.personal,...data.personal},financial:{...defaults.financial,...data.financial},serviceSpecific:{...defaults.serviceSpecific,...data.serviceSpecific},consents:{...defaults.consents,...data.consents},referralCode:data.referralCode||params.get('ref')||''});setDraftMessage('Saved draft restored from MongoDB.')},[savedDraft.data,form,params]);
  const saveDraft=useMutation({mutationFn:async(values)=>{if(draftSession)return(await api.patch(`/applications/public/drafts/${draftSession.draftId}`,values,{headers:{'x-resume-token':draftSession.resumeToken}})).data.data;return(await api.post('/applications/public/drafts',values)).data.data},onSuccess:(data)=>{const next=data.resumeToken?{draftId:data.draftId,resumeToken:data.resumeToken}:draftSession;if(next){localStorage.setItem(draftStorageKey,JSON.stringify(next));setDraftSession(next)}setDraftMessage(data.message||'Draft saved.')}});
  const referralValidation=useMutation({mutationFn:async(referralCode)=>(await api.post('/applications/public/referrals/validate',{referralCode})).data.data});
  const submission=useMutation({mutationFn:async(values)=>(await api.post('/applications/public/submit',{...values,...(draftSession?{draftId:draftSession.draftId}:{})},{headers:draftSession?{'x-resume-token':draftSession.resumeToken}:{}})).data.data,onSuccess:()=>{localStorage.removeItem(draftStorageKey);trackEvent('application_submitted',{service:form.getValues('service')})},onError:(error)=>{if(error.response?.data?.error?.code==='REFERRAL_INVALID'){setStep(3);form.setError('referralCode',{type:'server',message:'This referral code is not valid or active. Check it or remove it to continue.'})}}});
  const selectedService=services.data?.find((item)=>item._id===form.watch('service'));const isLoan=selectedService?.category==='Loans';const amountLabel=selectedService?.category==='Insurance'?'Preferred cover amount (₹)':selectedService?.category==='Wealth & Investments'?'Planned investment amount (₹)':'Requested loan amount (₹)';
  const referralField=form.register('referralCode',{maxLength:{value:40,message:'Referral code is too long'},setValueAs:(value)=>String(value||'').trim().toUpperCase()});
  async function next(){if(!(await form.trigger(fieldsByStep[step])))return;if(step===3){const code=form.getValues('referralCode')?.trim();if(code){try{await referralValidation.mutateAsync(code)}catch(error){form.setError('referralCode',{type:'validate',message:apiMessage(error)});return}}}if(step===0)trackEvent('application_started',{service:form.getValues('service')});setStep((value)=>Math.min(steps.length-1,value+1))}
  function save(){const values=form.getValues();if(!values.service){form.setError('service',{message:'Choose a service before saving'});return}saveDraft.mutate(values)}
  function discardLocalDraft(){localStorage.removeItem(draftStorageKey);setDraftSession(null);setDraftMessage('');form.reset({...defaults,referralCode:params.get('ref')||''});setStep(0)}
  if(submission.isSuccess)return <section className="page-hero"><Seo title="Application Received | VFS Groups" description="Your VFS Groups application has been received." path="/apply"/><div className="shell narrow success-panel"><CheckCircle2/><span className="eyebrow">Application received</span><h1>{submission.data.applicationId}</h1><p>{submission.data.acknowledgement}</p><div className="ack-grid"><div><span>Lead ID</span><strong>{submission.data.leadId}</strong></div><div><span>Status</span><strong>{submission.data.status}</strong></div></div><div className="button-row"><Link className="button button-gold" to="/track">Track application</Link><Link className="button button-outline" to="/services">Return to services</Link></div></div></section>;
  return <><Seo title="Apply for Financial Service Assistance | VFS Groups" description="Save and submit a secure VFS Groups application for loan, insurance, or investment assistance." path="/apply"/><section className="page-hero compact-hero"><div className="shell"><Breadcrumbs items={[{label:'Apply'}]}/><span className="eyebrow">Secure application</span><h1>Tell us what you need, one clear step at a time.</h1><p>Salaried and self-employed customers can apply with or without ITRs. A low CIBIL score does not prevent you from asking VFS Group for assistance.</p></div></section><section className="section"><div className="shell application-layout"><aside className="application-progress"><span>Application progress</span><ol>{steps.map((label,index)=><li className={index===step?'active':index<step?'complete':''} key={label}><i>{index<step?'✓':index+1}</i>{label}</li>)}</ol></aside><form className="form-card application-form" onSubmit={form.handleSubmit((values)=>submission.mutate(values))}><div className="form-step-title"><span>Step {step+1} of {steps.length}</span><h2>{stepTitle(step)}</h2></div>{savedDraft.isLoading&&<p className="notice">Restoring saved draft…</p>}{savedDraft.isError&&<p className="form-error">The saved draft is unavailable or expired. You can start a new application.</p>}
  {step===0&&<label>Financial service<select {...form.register('service',{required:'Choose a service'})}><option value="">Choose a published service</option>{services.data?.map((item)=><option key={item._id} value={item._id}>{item.name}</option>)}</select><Error form={form} name="service"/></label>}
  {step===1&&<div className="form-grid"><Field label="Full name" name="personal.fullName" form={form} rules={{required:'Enter your full name',minLength:{value:2,message:'Enter at least 2 characters'}}}/><Field label="Mobile" name="personal.mobile" type="tel" inputMode="tel" form={form} rules={{required:'Enter your mobile number',pattern:{value:mobilePattern,message:mobileErrorMessage},setValueAs:sanitizeMobile}}/><Field label="Email" name="personal.email" type="email" form={form} rules={{required:'Enter your email'}}/><Field label="Date of birth" name="personal.dateOfBirth" type="date" form={form} rules={{required:'Enter your date of birth'}}/><Field label="City" name="personal.city" form={form} rules={{required:'Enter your city'}}/><Field label="State" name="personal.state" form={form} rules={{required:'Enter your state'}}/><Field label="PIN code" name="personal.pinCode" inputMode="numeric" form={form} rules={{required:'Enter your PIN code',pattern:{value:/^\d{6}$/,message:'Enter a 6-digit PIN code'}}}/></div>}
  {step===2&&<><div className="profile-note"><strong>Share what is available.</strong><span>ITRs and a high credit score are not required to start a conversation with VFS Group.</span></div><div className="form-grid"><label>Income profile<select {...form.register('financial.employmentType',{required:true})}><option value="salaried">Salaried</option><option value="self_employed">Self-employed</option><option value="business">Business</option><option value="other">Other</option></select></label><Field label="Employer / business" name="financial.employerOrBusinessName" form={form}/><CurrencyField label="Monthly income" name="financial.monthlyIncome" form={form}/><CurrencyField label="Annual turnover" name="financial.annualTurnover" form={form}/>{isLoan&&<><label>ITR availability<select {...form.register('financial.itrStatus')}><option value="available">ITRs available</option><option value="not_available">No ITRs available</option><option value="not_sure">Not sure</option></select></label><label>Credit profile<select {...form.register('financial.creditProfile')}><option value="low">Low CIBIL score</option><option value="fair">Fair CIBIL score</option><option value="good">Good CIBIL score</option><option value="not_sure">Not known / not sure</option></select></label></>}<CurrencyField label="Existing monthly EMI" name="financial.existingEmi" form={form}/><CurrencyField label={amountLabel.replace(' (₹)','')} name="financial.requestedAmount" form={form} required/></div></>}
  {step===3&&<><label>Describe the requirement<textarea rows="7" {...form.register('serviceSpecific.requirementSummary',{required:'Describe the requirement',minLength:{value:10,message:'Add at least 10 characters'}})}/><Error form={form} name="serviceSpecific.requirementSummary"/></label><label>Referral code (optional)<input className="referral-input" aria-invalid={Boolean(fieldError(form,'referralCode'))} {...referralField} onChange={(event)=>{form.clearErrors('referralCode');referralValidation.reset();referralField.onChange(event)}}/><small>{params.get('ref')?'Filled from your referral link. You can correct or remove it before we verify it.':'Enter an active VFS contractor referral code if applicable.'}</small><Error form={form} name="referralCode"/>{referralValidation.isSuccess&&<small className="field-success">Referral code verified.</small>}</label></>}
  {step===4&&<div className="document-step"><FileLock2/><h3>Protected upload follows verification</h3><p>After submission, use the application ID and registered mobile on the tracking page. A short-lived verification code unlocks the document centre, where requested files are sent to authenticated Cloudinary storage.</p><p className="disclaimer">This prevents sensitive files from being attached before application ownership is verified.</p></div>}
  {step===5&&<div className="consent-list"><label className="checkbox"><input type="checkbox" {...form.register('consents.privacy',{required:'Privacy consent is required'})}/><span>I consent to processing of my information as described in the privacy notice.</span></label><Error form={form} name="consents.privacy"/><label className="checkbox"><input type="checkbox" {...form.register('consents.communication')}/><span>I agree to receive application-related communication through configured channels.</span></label><label className="checkbox"><input type="checkbox" {...form.register('consents.accuracy',{required:'Accuracy declaration is required'})}/><span>I declare that the information supplied is accurate to the best of my knowledge.</span></label><Error form={form} name="consents.accuracy"/><label className="checkbox"><input type="checkbox" {...form.register('consents.terms',{required:'Terms acceptance is required'})}/><span>I accept the terms and financial service disclaimer.</span></label><Error form={form} name="consents.terms"/><input className="honeypot" tabIndex="-1" autoComplete="off" {...form.register('website')}/></div>}
  <div className="draft-bar"><button type="button" className="inline-link" onClick={save} disabled={saveDraft.isPending}><Save size={17}/>{saveDraft.isPending?'Saving…':draftSession?'Update saved draft':'Save and continue later'}</button>{draftSession&&<button type="button" className="text-button" onClick={discardLocalDraft}>Start new</button>}</div>{draftMessage&&<p className="form-success">{draftMessage}</p>}{saveDraft.isError&&<p className="form-error">{apiMessage(saveDraft.error)}</p>}
  <div className="application-actions">{step>0?<button type="button" className="button button-outline" onClick={()=>setStep((value)=>value-1)}><ArrowLeft size={17}/> Back</button>:<span/>}{step<steps.length-1?<button type="button" className="button button-gold" onClick={next} disabled={referralValidation.isPending}>{referralValidation.isPending?'Checking code…':<>Continue <ArrowRight size={17}/></>}</button>:<button className="button button-gold" disabled={submission.isPending}>{submission.isPending?'Submitting…':'Submit application'}</button>}</div>{submission.isError&&errorCode(submission.error)!=='REFERRAL_INVALID'&&<p className="form-error" role="alert">{apiMessage(submission.error)}</p>}</form></div></section></>;
}
function stepTitle(step){return ['Choose a service','Personal information','Financial information','Requirement and referral','Document security','Review and consent'][step]}
function Field({label,name,type='text',inputMode,form,rules}){const error=fieldError(form,name);return <label>{label}<input type={type} inputMode={inputMode} aria-invalid={Boolean(error)} onInput={type==='tel'?sanitizeMobileEvent:undefined} {...form.register(name,rules)}/><Error form={form} name={name}/></label>}
function CurrencyField({label,name,form,required=false}){const value=form.watch(name);return <label>{label} (₹)<input type="number" min="0" step="1" inputMode="numeric" {...form.register(name,{valueAsNumber:true,min:{value:0,message:'Amount cannot be negative'},...(required?{required:'Enter an amount'}:{})})}/>{Number(value)>0&&<small>{new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(value)}</small>}<Error form={form} name={name}/></label>}
function fieldError(form,name){return name.split('.').reduce((value,key)=>value?.[key],form.formState.errors)}
function Error({form,name}){const error=fieldError(form,name);return error?<small className="field-error" role="alert">{error.message}</small>:null}
function errorCode(error){return error.response?.data?.error?.code}
