import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertCircle, ArrowLeft, ArrowRight, CheckCircle2, Download, MessageCircle, Save, UserRound } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useForm } from 'react-hook-form';
import { Link, useSearchParams } from 'react-router-dom';
import { Breadcrumbs } from '../components/Breadcrumbs.jsx';
import { LocationFields } from '../components/LocationFields.jsx';
import { Seo } from '../components/Seo.jsx';
import { INDIA_COUNTRY } from '../data/indiaLocations.js';
import { api, apiMessage } from '../services/api.js';
import { trackEvent } from '../services/analytics.js';
import { mobileErrorMessage, mobilePattern, sanitizeMobile, sanitizeMobileEvent } from '../utils/validation.js';

const steps=['Service','Personal','Financial','Requirement','Consent'];
const fieldsByStep=[['service'],['personal.fullName','personal.mobile','personal.email','personal.dateOfBirth','personal.country','personal.city','personal.state','personal.pinCode'],['financial.employmentType','financial.requestedAmount'],['serviceSpecific.requirementSummary','referralCode'],['consents.privacy','consents.accuracy','consents.terms']];
const emailPattern=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const draftStorageKey='vfs_application_draft';
const defaults={service:'',personal:{fullName:'',mobile:'',email:'',dateOfBirth:'',country:INDIA_COUNTRY,city:'',state:'',pinCode:''},financial:{employmentType:'salaried',employerOrBusinessName:'',monthlyIncome:0,annualTurnover:0,existingEmi:0,requestedAmount:0,itrStatus:'not_sure',creditProfile:'not_sure'},serviceSpecific:{requirementSummary:''},referralCode:'',consents:{privacy:false,communication:false,accuracy:false,terms:false},website:''};
function storedDraft(){try{return JSON.parse(localStorage.getItem(draftStorageKey))||null}catch{return null}}

export function ApplyPage(){
  const [params]=useSearchParams(); const queryClient=useQueryClient(); const [step,setStep]=useState(0); const [draftSession,setDraftSession]=useState(storedDraft); const [draftMessage,setDraftMessage]=useState(''); const [validationMessage,setValidationMessage]=useState('');
  const services=useQuery({queryKey:['services'],queryFn:async()=>(await api.get('/services')).data.data});
  const session=useQuery({queryKey:['session'],queryFn:async()=>(await api.get('/auth/me')).data.data.user,retry:false,staleTime:30_000});
  const isCustomer=session.data?.roles?.some((role)=>role.slug==='customer')||false;
  const customerDraft=useQuery({queryKey:['customer-application-draft',session.data?._id],enabled:isCustomer,queryFn:async()=>(await api.get('/applications/customer/draft')).data.data,retry:false});
  const form=useForm({defaultValues:{...defaults,referralCode:params.get('ref')||''}});
  const savedDraft=useQuery({queryKey:['application-draft',draftSession?.draftId],enabled:Boolean(draftSession?.draftId&&draftSession?.resumeToken),queryFn:async()=>(await api.get(`/applications/public/drafts/${draftSession.draftId}`,{headers:{'x-resume-token':draftSession.resumeToken}})).data.data,retry:false});
  useEffect(()=>{const slug=params.get('service');const item=services.data?.find((entry)=>entry.slug===slug);if(item&&!draftSession)form.setValue('service',item._id)},[params,services.data,form,draftSession]);
  useEffect(()=>{if(!savedDraft.data||draftSession?.kind==='account')return;form.reset(formValues(savedDraft.data,params));setDraftMessage('Device draft restored.')},[savedDraft.data,form,params,draftSession?.kind]);
  useEffect(()=>{if(!customerDraft.data)return;const {account,draft}=customerDraft.data;if(draft){if(draftSession?.kind==='account'&&draftSession.draftId===draft.draftId)return;form.reset(formValues(draft,params));setDraftSession({draftId:draft.draftId,kind:'account'});localStorage.removeItem(draftStorageKey);setDraftMessage('Draft restored from your customer account.');return}if(draftSession?.resumeToken)return;const current=form.getValues();form.reset({...current,personal:{...current.personal,...account,dateOfBirth:current.personal.dateOfBirth||'',pinCode:current.personal.pinCode||''}});setDraftMessage(`Signed in as ${account.fullName}. Your account details were filled in.`)},[customerDraft.data,form,params,draftSession]);
  const saveDraft=useMutation({mutationFn:async(values)=>{if(isCustomer)return(await api.put('/applications/customer/draft',values)).data.data;if(draftSession?.resumeToken)return(await api.patch(`/applications/public/drafts/${draftSession.draftId}`,values,{headers:{'x-resume-token':draftSession.resumeToken}})).data.data;return(await api.post('/applications/public/drafts',values)).data.data},onSuccess:(data)=>{if(isCustomer){localStorage.removeItem(draftStorageKey);setDraftSession({draftId:data.draftId,kind:'account'});queryClient.setQueryData(['customer-application-draft',session.data?._id],(current)=>current?{...current,draft:data}:current)}else{const next=data.resumeToken?{draftId:data.draftId,resumeToken:data.resumeToken,kind:'device'}:draftSession;if(next){localStorage.setItem(draftStorageKey,JSON.stringify(next));setDraftSession(next)}}setDraftMessage(data.message||'Draft saved.')}});
  const deleteDraft=useMutation({mutationFn:async()=>isCustomer?api.delete('/applications/customer/draft'):Promise.resolve(),onSuccess:()=>resetApplication()});
  const referralValidation=useMutation({mutationFn:async(referralCode)=>(await api.post('/applications/public/referrals/validate',{referralCode})).data.data});
  const submission=useMutation({mutationFn:async(values)=>{const accountSubmission=isCustomer||draftSession?.kind==='account';const url=accountSubmission?'/applications/customer/submit':'/applications/public/submit';const headers=!accountSubmission&&draftSession?.resumeToken?{'x-resume-token':draftSession.resumeToken}:{};return(await api.post(url,{...values,...(draftSession?.draftId?{draftId:draftSession.draftId}:{})},{headers})).data.data},onSuccess:()=>{localStorage.removeItem(draftStorageKey);queryClient.removeQueries({queryKey:['customer-application-draft']});trackEvent('application_submitted',{service:form.getValues('service')})},onError:(error)=>showSubmissionError(error)});
  const selectedService=services.data?.find((item)=>item._id===form.watch('service'));const isLoan=selectedService?.category==='Loans';const amountLabel=selectedService?.category==='Insurance'?'Preferred cover amount (₹)':selectedService?.category==='Wealth & Investments'?'Planned investment amount (₹)':'Requested loan amount (₹)';
  const referralField=form.register('referralCode',{maxLength:{value:40,message:'Referral code is too long'},setValueAs:(value)=>String(value||'').trim().toUpperCase()});
  async function next(){setValidationMessage('');if(!(await form.trigger(fieldsByStep[step]))){showClientErrors(form.formState.errors,step);return}if(step===3){const code=form.getValues('referralCode')?.trim();if(code){try{await referralValidation.mutateAsync(code)}catch(error){form.setError('referralCode',{type:'validate',message:apiMessage(error)});setValidationMessage('Please correct the highlighted referral code before continuing.');focusField('referralCode');return}}}if(step===0)trackEvent('application_started',{service:form.getValues('service')});setStep((value)=>Math.min(steps.length-1,value+1));window.scrollTo({top:0,behavior:'smooth'})}
  function save(){const values=form.getValues();if(!values.service){setStep(0);form.setError('service',{message:'Choose a service before saving'});setValidationMessage('Choose a service before saving your draft.');focusField('service');return}saveDraft.mutate(values)}
  function resetApplication(){localStorage.removeItem(draftStorageKey);setDraftSession(null);setDraftMessage('');setValidationMessage('');form.reset({...defaults,referralCode:params.get('ref')||''});setStep(0);queryClient.setQueryData(['customer-application-draft',session.data?._id],(current)=>current?{...current,draft:null}:current)}
  function discardDraft(){if(draftSession?.kind==='account'&&isCustomer)deleteDraft.mutate();else resetApplication()}
  function focusField(name){window.setTimeout(()=>{form.setFocus(name);document.querySelector(`[name="${name}"]`)?.scrollIntoView({behavior:'smooth',block:'center'})},0)}
  function showClientErrors(errors,fallbackStep=step){const paths=errorPaths(errors);const target=paths.length?Math.min(...paths.map(fieldStep)):fallbackStep;setStep(target);setValidationMessage(`Please correct the highlighted field${paths.length===1?'':'s'} in ${steps[target]}.`);const first=paths.find((path)=>fieldStep(path)===target);if(first)focusField(first)}
  function showSubmissionError(error){const fields={...(error.response?.data?.error?.fields||{})};if(errorCode(error)==='REFERRAL_INVALID'&&!fields.referralCode)fields.referralCode='This referral code is not valid or active. Check it or remove it to continue.';if(errorCode(error)==='SERVICE_UNAVAILABLE'&&!fields.service)fields.service='This service is no longer available. Choose another service.';const names=Object.keys(fields);if(!names.length)return;names.forEach((name)=>form.setError(name,{type:'server',message:fields[name]}));const target=Math.min(...names.map(fieldStep));setStep(target);setValidationMessage(`We found ${names.length===1?'a problem':'problems'} in ${steps[target]}. Correct the red field${names.length===1?'':'s'} and continue.`);focusField(names.find((name)=>fieldStep(name)===target)||names[0])}
  function submit(values){setValidationMessage('');submission.mutate(values)}
  if(submission.isSuccess)return <section className="page-hero apply-success-hero"><Seo title="Application Received | VFS Groups" description="Your VFS Groups application has been received." path="/apply"/><div className="shell narrow success-panel"><CheckCircle2/><span className="eyebrow">Application received</span><h1>{submission.data.applicationId}</h1><p>{submission.data.acknowledgement}</p><div className="ack-grid"><div><span>Lead ID</span><strong>{submission.data.leadId}</strong></div><div><span>Status</span><strong>{submission.data.status}</strong></div></div><div className="application-next-steps" aria-label="What happens next"><span>Application submitted</span><ArrowRight/><span>VFS review</span><ArrowRight/><span>Call or meeting</span><ArrowRight/><span>Provider decision</span></div><p className="application-id-reminder">Save your application ID. VFS Groups will call you and coordinate any required documents in person.</p><div className="button-row application-success-actions"><Link className="button button-gold" to="/track">Track application</Link><button className="button button-outline" type="button" onClick={()=>downloadAcknowledgement(submission.data)}><Download/> Download ID</button><a className="button button-outline" href={whatsAppShareUrl(submission.data)} target="_blank" rel="noreferrer"><MessageCircle/> Share on WhatsApp</a><Link className="button button-outline" to="/services">Return to services</Link></div></div></section>;
  return <><Seo title="Apply for Financial Service Assistance | VFS Groups" description="Save and submit a secure VFS Groups application for loan, insurance, or investment assistance." path="/apply"/><section className="page-hero compact-hero apply-page-hero"><div className="shell"><Breadcrumbs items={[{label:'Apply'}]}/><span className="eyebrow">Secure application</span><h1>Tell us what you need, one clear step at a time.</h1><p>Salaried and self-employed customers can apply with or without ITRs. A low CIBIL score does not prevent you from asking VFS Group for assistance.</p></div></section><section className="section"><div className="shell application-layout"><aside className="application-progress"><span>Application progress</span><ol>{steps.map((label,index)=><li className={index===step?'active':index<step?'complete':''} key={label}><i>{index<step?'✓':index+1}</i>{label}</li>)}</ol></aside><form className="form-card application-form" onSubmit={form.handleSubmit(submit,(errors)=>showClientErrors(errors))} noValidate><div className="form-step-title"><span>Step {step+1} of {steps.length}</span><h2>{stepTitle(step)}</h2></div>{isCustomer&&<div className="account-draft-note"><UserRound/><span><strong>Signed in as {session.data.fullName}</strong>Your draft is saved securely to your customer account.</span></div>}{(savedDraft.isLoading||customerDraft.isLoading)&&<p className="notice">Restoring saved draft…</p>}{savedDraft.isError&&<p className="form-error">The device draft is unavailable or expired. You can start a new application.</p>}{customerDraft.isError&&<p className="form-error">We could not load your account draft. Please refresh or try again.</p>}{validationMessage&&<p className="form-error application-error-summary" role="alert"><AlertCircle/>{validationMessage}</p>}
  {step===0&&<label>Financial service<select aria-invalid={Boolean(fieldError(form,'service'))} {...form.register('service',{required:'Choose a service'})}><option value="">Choose a published service</option>{services.data?.map((item)=><option key={item._id} value={item._id}>{item.name}</option>)}</select><Error form={form} name="service"/></label>}
  {step===1&&<div className="form-grid"><Field label="Full name" name="personal.fullName" form={form} rules={{required:'Enter your full name',minLength:{value:2,message:'Enter at least 2 characters'}}}/><Field label="Mobile" name="personal.mobile" type="tel" inputMode="tel" form={form} rules={{required:'Enter your mobile number',pattern:{value:mobilePattern,message:mobileErrorMessage},setValueAs:sanitizeMobile}}/><Field label="Email" name="personal.email" type="email" form={form} rules={{required:'Enter your email',pattern:{value:emailPattern,message:'Enter a valid email address'}}}/><Field label="Date of birth" name="personal.dateOfBirth" type="date" max={today()} form={form} rules={{required:'Enter your date of birth',validate:(value)=>!value||value<=today()||'Date of birth cannot be in the future'}}/><LocationFields form={form} prefix="personal"/><Field label="PIN code" name="personal.pinCode" inputMode="numeric" form={form} rules={{required:'Enter your PIN code',pattern:{value:/^\d{6}$/,message:'Enter a 6-digit PIN code'}}}/></div>}
  {step===2&&<><div className="profile-note"><strong>Share what is available.</strong><span>ITRs and a high credit score are not required to start a conversation with VFS Group.</span></div><div className="form-grid"><label>Income profile<select {...form.register('financial.employmentType',{required:true})}><option value="salaried">Salaried</option><option value="self_employed">Self-employed</option><option value="business">Business</option><option value="other">Other</option></select></label><Field label="Employer / business" name="financial.employerOrBusinessName" form={form}/><CurrencyField label="Monthly income" name="financial.monthlyIncome" form={form}/><CurrencyField label="Annual turnover" name="financial.annualTurnover" form={form}/>{isLoan&&<><label>ITR availability<select {...form.register('financial.itrStatus')}><option value="available">ITRs available</option><option value="not_available">No ITRs available</option><option value="not_sure">Not sure</option></select></label><label>Credit profile<select {...form.register('financial.creditProfile')}><option value="low">Low CIBIL score</option><option value="fair">Fair CIBIL score</option><option value="good">Good CIBIL score</option><option value="not_sure">Not known / not sure</option></select></label></>}<CurrencyField label="Existing monthly EMI" name="financial.existingEmi" form={form}/><CurrencyField label={amountLabel.replace(' (₹)','')} name="financial.requestedAmount" form={form} required/></div></>}
  {step===3&&<><label>Describe the requirement<textarea rows="7" aria-invalid={Boolean(fieldError(form,'serviceSpecific.requirementSummary'))} {...form.register('serviceSpecific.requirementSummary',{required:'Describe the requirement',minLength:{value:10,message:'Add at least 10 characters'}})}/><Error form={form} name="serviceSpecific.requirementSummary"/></label><label>Referral code (optional)<input className="referral-input" aria-invalid={Boolean(fieldError(form,'referralCode'))} {...referralField} onChange={(event)=>{form.clearErrors('referralCode');referralValidation.reset();referralField.onChange(event)}}/><small>{params.get('ref')?'Filled from your referral link. You can correct or remove it before we verify it.':'Enter an active VFS contractor referral code if applicable.'}</small><Error form={form} name="referralCode"/>{referralValidation.isSuccess&&<small className="field-success">Referral code verified.</small>}</label></>}
  {step===4&&<div className="consent-list"><div className="profile-note"><strong>Documents are handled in person.</strong><span>After reviewing your application, VFS Groups will call you and explain what to bring. Do not upload sensitive documents on this website.</span></div><label className="checkbox"><input type="checkbox" {...form.register('consents.privacy',{required:'Privacy consent is required'})}/><span>I consent to processing of my information as described in the privacy notice.</span></label><Error form={form} name="consents.privacy"/><label className="checkbox"><input type="checkbox" {...form.register('consents.communication')}/><span>I agree to receive application-related communication through configured channels.</span></label><label className="checkbox"><input type="checkbox" {...form.register('consents.accuracy',{required:'Accuracy declaration is required'})}/><span>I declare that the information supplied is accurate to the best of my knowledge.</span></label><Error form={form} name="consents.accuracy"/><label className="checkbox"><input type="checkbox" {...form.register('consents.terms',{required:'Terms acceptance is required'})}/><span>I accept the terms and financial service disclaimer.</span></label><Error form={form} name="consents.terms"/><input className="honeypot" tabIndex="-1" autoComplete="off" {...form.register('website')}/></div>}
  <div className="draft-bar"><div className="draft-save-options"><button type="button" className="inline-link" onClick={save} disabled={saveDraft.isPending}><Save size={17}/>{saveDraft.isPending?'Saving…':isCustomer?(draftSession?.kind==='account'?'Update account draft':'Save to my account'):(draftSession?'Update device draft':'Save on this device')}</button>{!isCustomer&&!session.isLoading&&<Link className="account-save-link" to="/customer/sign-in?next=/apply">Sign in to save across devices</Link>}</div>{draftSession&&<button type="button" className="text-button" onClick={discardDraft} disabled={deleteDraft.isPending}>{deleteDraft.isPending?'Starting…':'Start new'}</button>}</div>{draftMessage&&<p className="form-success">{draftMessage}</p>}{saveDraft.isError&&<p className="form-error">{apiMessage(saveDraft.error)}</p>}{deleteDraft.isError&&<p className="form-error">{apiMessage(deleteDraft.error)}</p>}
  <div className="application-actions">{step>0?<button type="button" className="button button-outline" onClick={()=>{setValidationMessage('');setStep((value)=>value-1)}}><ArrowLeft size={17}/> Back</button>:<span/>}{step<steps.length-1?<button type="button" className="button button-gold" onClick={next} disabled={referralValidation.isPending}>{referralValidation.isPending?'Checking code…':<>Continue <ArrowRight size={17}/></>}</button>:<button className="button button-gold" disabled={submission.isPending}>{submission.isPending?'Submitting…':'Submit application'}</button>}</div>{submission.isError&&!hasServerFields(submission.error)&&errorCode(submission.error)!=='REFERRAL_INVALID'&&<p className="form-error" role="alert">{apiMessage(submission.error)}</p>}</form></div></section></>;
}
function stepTitle(step){return ['Choose a service','Personal information','Financial information','Requirement and referral','Review and consent'][step]}
function Field({label,name,type='text',inputMode,max,form,rules}){const error=fieldError(form,name);return <label>{label}<input type={type} inputMode={inputMode} max={max} aria-invalid={Boolean(error)} onInput={type==='tel'?sanitizeMobileEvent:undefined} {...form.register(name,rules)}/><Error form={form} name={name}/></label>}
function CurrencyField({label,name,form,required=false}){const value=form.watch(name);const error=fieldError(form,name);return <label>{label} (₹)<input type="number" min={required?'1':'0'} step="1" inputMode="numeric" aria-invalid={Boolean(error)} {...form.register(name,{valueAsNumber:true,min:{value:required?1:0,message:required?'Enter an amount greater than 0':'Amount cannot be negative'},...(required?{required:'Enter an amount'}:{})})}/>{Number(value)>0&&<small>{new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(value)}</small>}<Error form={form} name={name}/></label>}
function fieldError(form,name){return name.split('.').reduce((value,key)=>value?.[key],form.formState.errors)}
function Error({form,name}){const error=fieldError(form,name);return error?<small className="field-error" role="alert">{error.message}</small>:null}
function errorCode(error){return error.response?.data?.error?.code}
function hasServerFields(error){return Boolean(Object.keys(error.response?.data?.error?.fields||{}).length)}
function fieldStep(name){if(name==='service')return 0;if(name.startsWith('personal.'))return 1;if(name.startsWith('financial.'))return 2;if(name.startsWith('serviceSpecific.')||name==='referralCode')return 3;if(name.startsWith('consents.')||name==='website')return 4;return 0}
function errorPaths(errors,prefix=''){return Object.entries(errors||{}).flatMap(([key,value])=>{const path=prefix?`${prefix}.${key}`:key;if(value?.message||value?.type)return[path];return value&&typeof value==='object'?errorPaths(value,path):[]})}
function formValues(data,params){return {...defaults,...data,personal:{...defaults.personal,...data.personal,dateOfBirth:dateOnly(data.personal?.dateOfBirth)},financial:{...defaults.financial,...data.financial},serviceSpecific:{...defaults.serviceSpecific,...data.serviceSpecific},consents:{...defaults.consents,...data.consents},referralCode:data.referralCode||params.get('ref')||''}}
function dateOnly(value){return value?String(value).slice(0,10):''}
function today(){return new Date().toISOString().slice(0,10)}
function acknowledgementText(data){return `VFS GROUPS APPLICATION ACKNOWLEDGEMENT\n\nApplication ID: ${data.applicationId}\nLead ID: ${data.leadId}\nStatus: ${data.status}\n\nYour application was received for an initial completeness review. This is not a loan approval or offer.\n\nTrack your application on the VFS Groups website using the application ID and registered mobile number.`}
function downloadAcknowledgement(data){const blob=new Blob([acknowledgementText(data)],{type:'text/plain;charset=utf-8'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`${data.applicationId}-acknowledgement.txt`;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url)}
function whatsAppShareUrl(data){return `https://wa.me/?text=${encodeURIComponent(`VFS Groups application submitted.\nApplication ID: ${data.applicationId}\nLead ID: ${data.leadId}\nStatus: ${data.status}\nPlease keep this message for tracking.`)}`}
