import { zodResolver } from '@hookform/resolvers/zod';
import { useMutation } from '@tanstack/react-query';
import { CheckCircle2, UserPlus } from 'lucide-react';
import { useForm } from 'react-hook-form';
import { Link } from 'react-router-dom';
import { z } from 'zod';
import { api, apiMessage } from '../services/api.js';
const password=z.string().min(10,'Use at least 10 characters').regex(/[A-Z]/,'Include an uppercase letter').regex(/[a-z]/,'Include a lowercase letter').regex(/\d/,'Include a number');const schema=z.object({fullName:z.string().min(2),mobile:z.string().regex(/^\+?[1-9]\d{9,14}$/,'Enter a valid mobile number'),email:z.string().email().or(z.literal('')),password,city:z.string().min(2),state:z.string().min(2),consent:z.literal(true,{errorMap:()=>({message:'Consent is required'})})});
export function CustomerRegisterPage(){const form=useForm({resolver:zodResolver(schema),defaultValues:{fullName:'',mobile:'',email:'',password:'',city:'',state:'',consent:false}});const register=useMutation({mutationFn:async(values)=>(await api.post('/auth/customer/register',values)).data.data});if(register.isSuccess)return <section className="page-hero"><div className="shell narrow success-panel"><CheckCircle2/><span className="eyebrow">Account created</span><h1>Welcome, {register.data.user.fullName}.</h1><p>Your customer record and secure session were created through the API. Verification and customer application modules continue in the next phase.</p><Link className="button button-gold" to="/services">Explore services</Link></div></section>;return <section className="auth-section"><div className="auth-aside"><UserPlus/><span className="eyebrow">Customer registration</span><h1>Build a secure account for every next step.</h1><p>Your profile is stored in MongoDB and linked to a unique customer ID. A seeded customer role is required.</p></div><form className="form-card auth-form" onSubmit={form.handleSubmit((values)=>register.mutate(values))}><h2>Create customer account</h2><div className="form-grid"><Field label="Full name" name="fullName" form={form}/><Field label="Mobile number" name="mobile" form={form}/><Field label="Email (optional)" name="email" type="email" form={form}/><Field label="City" name="city" form={form}/><Field label="State" name="state" form={form}/></div><Field label="Password" name="password" type="password" form={form}/><label className="checkbox"><input type="checkbox" {...form.register('consent')}/><span>I accept the privacy notice and consent to creation of this account.</span></label>{form.formState.errors.consent&&<small className="field-error">{form.formState.errors.consent.message}</small>}<button className="button button-gold" disabled={register.isPending}>{register.isPending?'Creating account…':'Create secure account'}</button>{register.isError&&<p className="form-error" role="alert">{apiMessage(register.error)}</p>}<p>Already registered? <Link to="/sign-in">Sign in</Link></p></form></section>}
function Field({label,name,type='text',form}){return <label>{label}<input type={type} {...form.register(name)}/>{form.formState.errors[name]&&<small className="field-error">{form.formState.errors[name].message}</small>}</label>}
