import { useQuery } from '@tanstack/react-query';
import { ArrowRight, BadgeCheck, Building2, Calculator, CheckCircle2, FileCheck2, Headphones, Home, Landmark, LockKeyhole, MessageSquareText, ShieldCheck, Sparkles, TrendingUp, Users } from 'lucide-react';
import { Link } from 'react-router-dom';
import { api } from '../services/api.js';

const benefits = [
  [Landmark, 'Multiple financial products', 'Explore property, business, project, personal, and insurance assistance in one place.'],
  [FileCheck2, 'Documentation guidance', 'Understand commonly requested records and keep application actions visible.'],
  [LockKeyhole, 'Secure document handling', 'Protected delivery and authorization are built into the document architecture.'],
  [Headphones, 'Dedicated support', 'Use callbacks, support requests, and configured communication channels.'],
];
const steps = ['Select a financial service', 'Share your requirements', 'Upload requested documents', 'Application review and assistance', 'Submission to a relevant provider', 'Track application progress'];

export function HomePage() {
  const services = useQuery({ queryKey: ['services'], queryFn: async () => (await api.get('/services')).data.data });
  return <>
    <section className="hero"><div className="shell hero-grid"><div className="hero-copy"><span className="eyebrow"><Sparkles size={16} /> Thoughtful financial guidance</span><h1>Financial solutions for every stage of <em>growth.</em></h1><p>Explore suitable loan and insurance options with clear application assistance for individuals, families, professionals, businesses, and industrial customers.</p><div className="button-row"><Link className="button button-gold" to="/services">Explore financial solutions <ArrowRight size={18} /></Link><Link className="button button-outline" to="/eligibility">Check eligibility</Link></div><Link className="inline-link" to="/contact">Prefer a conversation? Request a callback <ArrowRight size={16} /></Link></div><div className="hero-visual" aria-label="Application assistance features"><div className="brand-orbit"><img src="/brand/vfs-groups-logo.png" alt="VFS Groups logo" /></div><div className="process-card"><span>Application journey</span><strong>Clear next steps</strong><div className="progress-track"><i /></div><ul><li><CheckCircle2 /> Requirements captured</li><li><FileCheck2 /> Document guidance</li><li><MessageSquareText /> Status communication</li></ul></div><div className="security-card"><ShieldCheck /><div><strong>Privacy by design</strong><span>Authorized access to sensitive records</span></div></div></div></div></section>
    <section className="trust-strip"><div className="shell trust-grid">{[[Landmark,'Multiple solutions'],[BadgeCheck,'Application assistance'],[Users,'Dedicated support'],[LockKeyhole,'Secure handling']].map(([Icon,label])=><div key={label}><Icon /><span>{label}</span></div>)}</div></section>
    <section className="section"><div className="shell"><div className="section-heading"><div><span className="eyebrow">Explore solutions</span><h2>Start with what you want to achieve.</h2></div><Link className="inline-link" to="/services">View all services <ArrowRight size={16} /></Link></div>{services.isLoading && <div className="card-grid" aria-label="Loading services">{Array.from({length:6},(_,index)=><div className="service-card skeleton" key={index} />)}</div>}{services.isError && <div className="notice error">Published services could not be loaded. Confirm that the API is running and reference data has been seeded.</div>}{services.data && <div className="card-grid">{services.data.slice(0,8).map((service)=><ServiceCard service={service} key={service._id} />)}</div>}</div></section>
    <section className="section finder-section"><div className="shell finder-grid"><div><span className="eyebrow">Smart service finder</span><h2>A better starting point than guesswork.</h2><p>Choose the purpose that best describes your requirement. The guided checker recommends relevant published services without promising eligibility or approval.</p><Link className="button button-gold" to="/eligibility">Find a relevant service <ArrowRight size={18} /></Link></div><div className="finder-options">{['Buying a home','Building property','Personal expenses','Business growth','Industrial property','Project development','Insurance protection','Transfer an existing loan'].map((label)=><Link to="/eligibility" key={label}>{label}<ArrowRight size={16}/></Link>)}</div></div></section>
    <section className="section"><div className="shell"><div className="section-heading compact"><div><span className="eyebrow">Why VFS Groups</span><h2>Practical support, designed around the journey.</h2></div></div><div className="benefit-grid">{benefits.map(([Icon,title,copy])=><article key={title}><Icon/><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
    <section className="section process-section"><div className="shell"><div className="section-heading"><div><span className="eyebrow">How it works</span><h2>Six clear steps from requirement to progress.</h2></div></div><ol className="steps">{steps.map((step,index)=><li key={step}><span>{String(index+1).padStart(2,'0')}</span><strong>{step}</strong></li>)}</ol><p className="disclaimer">Approvals, rates, eligibility, terms, charges, and disbursement depend on the relevant lender, insurer, financial institution, applicant profile, documentation, and applicable policies.</p></div></section>
    <section className="section tools-section"><div className="shell tools-grid"><Link to="/emi-calculator" className="tool-card"><Calculator/><span>Planning tool</span><h2>Estimate an illustrative EMI</h2><p>Explore monthly repayment, total interest, and total estimated repayment.</p><b>Open calculator <ArrowRight size={17}/></b></Link><Link to="/track" className="tool-card dark"><TrendingUp/><span>Secure tracking</span><h2>Check application progress</h2><p>Personal application information requires OTP verification against the registered mobile.</p><b>Track application <ArrowRight size={17}/></b></Link></div></section>
    <section className="final-cta"><div className="shell"><div><span className="eyebrow">We are here to help</span><h2>Need help choosing the right financial solution?</h2></div><div className="button-row"><Link className="button button-gold" to="/contact">Request a callback</Link><Link className="button button-light" to="/contact">Contact support</Link></div></div></section>
  </>;
}

function ServiceCard({ service }) {
  const icons = { 'Home & Property Finance': Home, 'Business & Industrial Finance': Building2, 'Project Finance': TrendingUp, 'Personal Finance': Users, Insurance: ShieldCheck }; const Icon = icons[service.category] || Landmark;
  return <article className="service-card"><div className="service-icon"><Icon /></div><span>{service.category}</span><h3>{service.name}</h3><p>{service.shortDescription}</p><div><Link to={`/services/${service.slug}`}>Learn more <ArrowRight size={16}/></Link><Link to={`/apply?service=${service.slug}`}>Apply</Link></div></article>;
}
