import { zodResolver } from '@hookform/resolvers/zod';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { Eye, EyeOff, LogIn, ShieldCheck } from 'lucide-react';
import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { Link, useNavigate } from 'react-router-dom';
import { z } from 'zod';
import { api, apiMessage } from '../services/api.js';

const schema=z.object({identifier:z.string().min(3,'Enter your mobile number or email'),password:z.string().min(1,'Enter your password')});
const config={customer:{title:'Customer sign in',dashboard:'/customer/dashboard',register:'/customer/sign-up'},contractor:{title:'Contractor sign in',dashboard:'/contractor/dashboard',register:'/contractor/sign-up'},admin:{title:'Admin sign in',dashboard:'/admin/dashboard'}};
export function PortalLoginPage({portal}){return <section className="auth-section"><div className="auth-aside"><ShieldCheck/><span className="eyebrow">{portal} portal</span><h1>{config[portal].title}</h1><p>Your role is verified by the backend before this workspace is opened.</p></div><PortalLoginForm portal={portal}/></section>}
export function PortalLoginForm({portal,showChooserLink=true}){const navigate=useNavigate();const queryClient=useQueryClient();const form=useForm({resolver:zodResolver(schema),defaultValues:{identifier:'',password:''}});const login=useMutation({mutationFn:async(values)=>(await api.post(`/auth/${portal}/login`,values)).data.data,onSuccess:({user})=>{queryClient.setQueryData(['session'],user);navigate(config[portal].dashboard,{replace:true})}});return <form className="form-card auth-form" onSubmit={form.handleSubmit((values)=>login.mutate(values))} noValidate><div className="form-title"><LogIn/><div><h2>{config[portal].title}</h2><p>Use your registered email or mobile.</p></div></div><Field label="Email or mobile" name="identifier" form={form}/><PasswordField form={form}/><button className="button button-gold" disabled={login.isPending}>{login.isPending?'Signing in…':'Sign in securely'}</button>{login.isError&&<p className="form-error" role="alert">{apiMessage(login.error)}</p>}{config[portal].register&&<p>Need an account? <Link to={config[portal].register}>Register here</Link></p>}{showChooserLink&&<Link className="inline-link" to="/sign-in">Choose another portal</Link>}</form>}
function Field({label,name,type='text',form}){return <label>{label}<input type={type} autoComplete={type==='password'?'current-password':'username'} {...form.register(name)}/>{form.formState.errors[name]&&<small className="field-error">{form.formState.errors[name].message}</small>}</label>}
function PasswordField({form}){const [visible,setVisible]=useState(false);const error=form.formState.errors.password;return <label>Password<div className="password-input"><input type={visible?'text':'password'} autoComplete="current-password" aria-invalid={Boolean(error)} {...form.register('password')}/><button type="button" onClick={()=>setVisible((value)=>!value)} aria-label={visible?'Hide password':'Show password'} title={visible?'Hide password':'Show password'}>{visible?<EyeOff/>:<Eye/>}</button></div>{error&&<small className="field-error" role="alert">{error.message}</small>}</label>}
