import { useQuery } from '@tanstack/react-query';
import { ArrowRight, CheckCircle2, FileText, MessageCircle, ShieldCheck } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { Seo } from '../components/Seo.jsx';
import { api } from '../services/api.js';

export function ServiceDetailPage() {
  const { slug } = useParams(); const service = useQuery({ queryKey: ['service', slug], queryFn: async () => (await api.get(`/services/${slug}`)).data.data });
  if (service.isLoading) return <div className="shell route-loading">Loading service information…</div>;
  if (service.isError) return <div className="shell route-loading"><h1>Service unavailable</h1><Link to="/services">Return to services</Link></div>;
  const item = service.data; const isLoan = item.category === 'Loans';
  return <><Seo title={item.seo?.title || `${item.name} | VFS Groups`} description={item.seo?.description || item.shortDescription} path={`/services/${item.slug}`} structuredData={{ '@context': 'https://schema.org', '@type': 'Service', name: item.name, description: item.overview, provider: { '@type': 'Organization', name: 'VFS Groups' }, areaServed: 'India', serviceType: item.category }}/><section className="service-hero"><div className="shell"><nav className="breadcrumbs" aria-label="Breadcrumb"><Link to="/">Home</Link><span>/</span><Link to="/services">Services</Link><span>/</span><b>{item.name}</b></nav><div><div><span className="eyebrow">{item.category}</span><h1>{item.name}</h1><p>{item.overview}</p><div className="button-row"><Link className="button button-gold" to={`/apply?service=${item.slug}`}>Apply for assistance <ArrowRight size={18}/></Link><Link className="button button-light" to="/contact">Request callback</Link></div></div><aside><ShieldCheck/><strong>{isLoan ? 'You can still speak with us' : 'Clear, guided assistance'}</strong><p>{isLoan ? 'Salaried or self-employed, with or without ITRs—even with a low CIBIL score. Final approval and terms are decided by the relevant lender.' : 'Product eligibility, benefits, premiums, risks, and outcomes depend on the selected provider and official terms.'}</p></aside></div></div></section><section className="section"><div className="shell detail-layout"><article className="detail-content"><DetailSection title="Who this may suit" items={item.suitableFor}/><DetailSection title="Key benefits" items={item.features}/><DetailSection title="Common requirements" items={item.useCases}/><DetailSection title={isLoan ? 'How VFS Group can assist' : 'Product considerations'} items={item.eligibility}/><DetailSection title="Documents that may be requested" items={item.documents} icon={FileText}/><div className="detail-section"><h2>Service journey</h2><ol className="numbered-list">{item.process.map((value, index) => <li key={value}><span>{index + 1}</span>{value}</li>)}</ol></div><DetailSection title="Important considerations" items={item.considerations}/><div className="detail-section"><h2>Frequently asked questions</h2>{item.faqs.map((faq) => <details key={faq.question}><summary>{faq.question}</summary><p>{faq.answer}</p></details>)}</div></article><aside className="detail-aside"><h2>Ready for the next step?</h2><p>Share your requirement or ask our team for help choosing a service.</p><Link className="button button-gold" to={`/apply?service=${item.slug}`}>Apply now</Link><Link className="button button-outline" to="/contact"><MessageCircle size={17}/> Request callback</Link></aside></div></section></>;
}

function DetailSection({ title, items = [], icon: Icon = CheckCircle2 }) { if (!items.length) return null; return <section className="detail-section"><h2>{title}</h2><ul className="check-list">{items.map((value) => <li key={value}><Icon/>{value}</li>)}</ul></section>; }
