import { zodResolver } from '@hookform/resolvers/zod';
import { useMutation } from '@tanstack/react-query';
import { LogIn, ShieldCheck } from 'lucide-react';
import { useForm } from 'react-hook-form';
import { Link } from 'react-router-dom';
import { z } from 'zod';
import { api, apiMessage } from '../services/api.js';
const schema=z.object({identifier:z.string().min(3,'Enter your mobile number or email'),password:z.string().min(1,'Enter your password')});
export function SignInPage(){const form=useForm({resolver:zodResolver(schema),defaultValues:{identifier:'',password:''}});const login=useMutation({mutationFn:async(values)=>(await api.post('/auth/login',values)).data.data});return <section className="auth-section"><div className="auth-aside"><ShieldCheck/><span className="eyebrow">Secure portal access</span><h1>Your application journey, in one place.</h1><p>Access is protected by server-side authentication, role permissions, and resource ownership checks.</p></div><form className="form-card auth-form" onSubmit={form.handleSubmit((values)=>login.mutate(values))}><div className="form-title"><LogIn/><div><h2>Sign in</h2><p>Use your registered email or mobile.</p></div></div><Field label="Email or mobile" name="identifier" form={form}/><Field label="Password" name="password" type="password" form={form}/><button className="button button-gold" disabled={login.isPending}>{login.isPending?'Signing in…':'Sign in securely'}</button>{login.isError&&<p className="form-error" role="alert">{apiMessage(login.error)}</p>}{login.isSuccess&&<div className="form-success" role="status">Signed in as {login.data.user.fullName}. Role dashboards will be enabled only as their database-backed API modules are completed.</div>}<p>New customer? <Link to="/customer/sign-up">Create an account</Link></p></form></section>}
function Field({label,name,type='text',form}){return <label>{label}<input type={type} autoComplete={type==='password'?'current-password':'username'} {...form.register(name)}/>{form.formState.errors[name]&&<small className="field-error">{form.formState.errors[name].message}</small>}</label>}
