import { useQuery } from '@tanstack/react-query';
import { Activity, LayoutDashboard, Network, Search, ShieldCheck, Users } from 'lucide-react';
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { DashboardShell } from '../../components/dashboard/DashboardShell.jsx';
import { DashboardTabs, Pagination } from '../../components/dashboard/DashboardTabs.jsx';
import { api, apiMessage } from '../../services/api.js';
import { formatDate, humanize } from '../../utils/dashboard.js';
import { ResponsiveTable } from './MemberDashboardPage.jsx';

const statuses = ['new', 'contacted', 'documents_pending', 'under_review', 'submitted_to_provider', 'approved', 'rejected', 'closed'];
const pageSize = 25;

export function AdminDashboardPage() {
  const [active, setActive] = useState('overview'); const [userPage, setUserPage] = useState(1); const [referralPage, setReferralPage] = useState(1);
  const [userSearch, setUserSearch] = useState(''); const [userRole, setUserRole] = useState('');
  const [loanSearch, setLoanSearch] = useState(''); const [loanRole, setLoanRole] = useState(''); const [loanStatus, setLoanStatus] = useState(''); const [dateFrom, setDateFrom] = useState(''); const [dateTo, setDateTo] = useState('');
  const summary = useQuery({ queryKey: ['dashboard', 'admin'], queryFn: async () => (await api.get('/dashboard/admin')).data.data });
  const users = useQuery({ queryKey: ['admin-users', userSearch, userRole, userPage], enabled: active === 'users', queryFn: async () => (await api.get('/dashboard/admin/users', { params: { q: userSearch, role: userRole, page: userPage, limit: pageSize } })).data });
  const loans = useQuery({ queryKey: ['admin-loan-referrals', loanSearch, loanRole, loanStatus, dateFrom, dateTo, referralPage], enabled: active === 'referrals', queryFn: async () => (await api.get('/dashboard/admin/loan-referrals', { params: { q: loanSearch, role: loanRole, status: loanStatus, dateFrom, dateTo, page: referralPage, limit: pageSize } })).data });
  if (summary.isLoading) return <div className="shell route-loading">Loading operational data…</div>;
  if (summary.isError) return <div className="shell route-loading"><h1>Admin dashboard unavailable</h1><p>{apiMessage(summary.error)}</p></div>;
  const data = summary.data;
  const tabs = [
    { id: 'overview', label: 'Overview', icon: LayoutDashboard },
    { id: 'users', label: 'Customers & contractors', icon: Users, count: data.metrics.totalUsers },
    { id: 'referrals', label: 'Service referrals', icon: Network, count: data.metrics.totalLoanReferrals },
    { id: 'activity', label: 'Recent activity', icon: Activity },
  ];
  return <DashboardShell role="admin" title="Operations">
    <section className="dashboard-welcome admin-welcome"><div><span className="eyebrow">Admin dashboard</span><h1>Operational visibility from live data.</h1><p>Use the tabs to work with registrations, referrals, applications, and activity without one long page.</p></div><ShieldCheck/></section>
    <DashboardTabs tabs={tabs} active={active} onChange={setActive} label="Admin operation sections"/>

    {active === 'overview' && <div className="tab-panel" role="tabpanel"><section className="metric-grid admin-metrics"><Metric label="Public applications" value={data.metrics.totalApplications}/><Metric label="Registered users" value={data.metrics.totalUsers}/><Metric label="Customers" value={data.metrics.totalCustomers}/><Metric label="Contractors" value={data.metrics.totalContractors}/><Metric label="Successful logins" value={data.metrics.totalSuccessfulLogins}/><Metric label="Unique users logged in" value={data.metrics.uniqueUsersLoggedIn}/><Metric label="Referred registrations" value={data.metrics.referredRegistrations}/><Metric label="Direct registrations" value={data.metrics.directRegistrations}/><Metric label="Referral codes" value={data.metrics.totalReferralCodes}/><Metric label="Service referrals" value={data.metrics.totalLoanReferrals}/></section><section className="dashboard-columns"><article className="dashboard-card"><span className="eyebrow">Application pipeline</span><h2>Applications by status</h2><ResponsiveTable columns={['Status', 'Applications']} rows={(data.applicationStatusTotals || []).map((item) => [humanize(item._id), item.count])} empty="No submitted public applications yet."/><Link className="inline-link tab-more" to="/admin/applications">Open application management →</Link></article><article className="dashboard-card"><span className="eyebrow">Referral performance</span><h2>Most-used referral codes</h2><ResponsiveTable columns={['Code', 'Owner', 'Registrations']} rows={data.mostUsedReferralCodes.map((item) => [<Link className="table-link" key={item.referralCode} to={`/admin/referrals/${item.referralCode}`}>{item.referralCode}</Link>, item.owner?.fullName || 'Unknown', item.registrations])} empty="No referred registrations yet."/></article></section><section className="dashboard-columns"><article className="dashboard-card"><span className="eyebrow">Customer referrals</span><h2>Top referring customers</h2><ReferrerTable items={data.topReferringCustomers}/></article><article className="dashboard-card"><span className="eyebrow">Contractor referrals</span><h2>Top referring contractors</h2><ReferrerTable items={data.topReferringContractors}/></article></section></div>}

    {active === 'users' && <section className="dashboard-card dashboard-section tab-panel" role="tabpanel"><div className="card-heading"><div><span className="eyebrow">User directory</span><h2>Customers and contractors</h2></div><Users/></div><div className="dashboard-filters"><label><Search/><input value={userSearch} onChange={(event) => { setUserSearch(event.target.value); setUserPage(1); }} placeholder="Name, email, phone, referral code"/></label><select aria-label="Filter users by role" value={userRole} onChange={(event) => { setUserRole(event.target.value); setUserPage(1); }}><option value="">All roles</option><option value="customer">Customers</option><option value="contractor">Contractors</option></select></div>{users.isLoading ? <div className="empty-state">Loading users…</div> : users.isError ? <p className="form-error">{apiMessage(users.error)}</p> : <><ResponsiveTable columns={['Name', 'Role', 'Contact', 'Referral code', 'Referred by', 'Registrations', 'Service referrals', 'Logins', 'Created']} rows={(users.data?.data || []).map((user) => [<Link key={user._id} className="table-link" to={`/admin/users/${user._id}`}>{user.fullName}</Link>, user.roles?.map((role) => role.name).join(', '), <span key="contact">{user.email || '—'}<small>{user.mobile}</small></span>, user.referralCode ? <Link key="code" className="table-link" to={`/admin/referrals/${user.referralCode}`}>{user.referralCode}</Link> : '—', user.referredBy?.fullName || 'Direct', user.referredUsersCount, user.loanReferralsCount, user.successfulLoginCount || 0, formatDate(user.createdAt)])} empty="No users match the current search."/><Pagination page={userPage} pages={users.data?.meta?.pages} total={users.data?.meta?.total} onChange={setUserPage} label="users"/></>}</section>}

    {active === 'referrals' && <div className="tab-panel" role="tabpanel"><section className="dashboard-card dashboard-section"><div className="card-heading"><div><span className="eyebrow">Service referral operations</span><h2>Customer and contractor submissions</h2></div><Activity/></div><div className="dashboard-filters"><label><Search/><input value={loanSearch} onChange={(event) => { setLoanSearch(event.target.value); setReferralPage(1); }} placeholder="ID, applicant, submitter, code"/></label><select aria-label="Filter referrals by role" value={loanRole} onChange={(event) => { setLoanRole(event.target.value); setReferralPage(1); }}><option value="">All roles</option><option value="customer">Customer</option><option value="contractor">Contractor</option></select><select aria-label="Filter referrals by status" value={loanStatus} onChange={(event) => { setLoanStatus(event.target.value); setReferralPage(1); }}><option value="">All statuses</option>{statuses.map((status) => <option value={status} key={status}>{humanize(status)}</option>)}</select><label className="date-filter"><span>From</span><input type="date" value={dateFrom} onChange={(event) => { setDateFrom(event.target.value); setReferralPage(1); }}/></label><label className="date-filter"><span>To</span><input type="date" value={dateTo} onChange={(event) => { setDateTo(event.target.value); setReferralPage(1); }}/></label></div>{loans.isLoading ? <div className="empty-state">Loading referrals…</div> : loans.isError ? <p className="form-error">{apiMessage(loans.error)}</p> : <><ResponsiveTable columns={['Referral ID', 'Applicant', 'Submitted by', 'Role', 'Referral code', 'Service', 'Submitted', 'Status']} rows={(loans.data?.data || []).map((item) => [item.referralId, item.applicant.fullName, <Link key="owner" className="table-link" to={`/admin/users/${item.submittedBy?._id}`}>{item.submittedBy?.fullName || 'Unknown'}</Link>, humanize(item.submitterRole), item.submitterReferralCode, item.service?.name || '—', formatDate(item.createdAt), humanize(item.status)])} empty="No service referrals match the current filters."/><Pagination page={referralPage} pages={loans.data?.meta?.pages} total={loans.data?.meta?.total} onChange={setReferralPage} label="service referrals"/></>}</section><section className="dashboard-card dashboard-section"><span className="eyebrow">Submission volume</span><h2>Service referrals by user</h2><ResponsiveTable columns={['User', 'Referral code', 'Submissions']} rows={data.loanReferralsByUser.map((item) => [<Link className="table-link" key={item.user._id} to={`/admin/users/${item.user._id}`}>{item.user.fullName}</Link>, item.user.referralCode, item.submissions])} empty="No service referrals yet."/></section></div>}

    {active === 'activity' && <div className="tab-panel" role="tabpanel"><section className="dashboard-columns"><article className="dashboard-card"><span className="eyebrow">Recent activity</span><h2>Recent registrations</h2><ResponsiveTable columns={['Name', 'Role', 'Code used', 'Date']} rows={data.recentRegistrations.map((item) => [<Link className="table-link" key={item._id} to={`/admin/users/${item._id}`}>{item.fullName}</Link>, item.roles.map((role) => role.name).join(', '), item.referredByCode || 'Direct', formatDate(item.createdAt)])} empty="No registrations yet."/></article><article className="dashboard-card"><span className="eyebrow">Login activity</span><h2>Recent successful logins</h2><ResponsiveTable columns={['User', 'Role', 'Date']} rows={data.recentLogins.map((item) => [item.user?.fullName || 'Unknown', humanize(item.role), formatDate(item.loginAt)])} empty="No login activity recorded."/></article></section><section className="dashboard-card dashboard-section"><span className="eyebrow">Recent service activity</span><h2>Recent service referrals</h2><ResponsiveTable columns={['ID', 'Applicant', 'Submitted by', 'Role', 'Code', 'Date', 'Status']} rows={data.recentLoanReferrals.map((item) => [item.referralId, item.applicant.fullName, item.submittedBy?.fullName || 'Unknown', humanize(item.submitterRole), item.submitterReferralCode, formatDate(item.createdAt), humanize(item.status)])} empty="No service referrals yet."/></section></div>}
  </DashboardShell>;
}

function Metric({ label, value }) { return <article className="metric-card"><span>{label}</span><strong>{value}</strong></article>; }
function ReferrerTable({ items }) { return <ResponsiveTable columns={['Owner', 'Referral code', 'Registrations']} rows={items.map((item) => [<Link className="table-link" key={item.owner._id} to={`/admin/users/${item.owner._id}`}>{item.owner.fullName}</Link>, item.owner.referralCode, item.registrations])} empty="No referred registrations yet."/>; }
