import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { FileText, Pencil, Save, ShieldCheck, Trash2, UserRound, Users } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useForm } from 'react-hook-form';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { DashboardShell } from '../../components/dashboard/DashboardShell.jsx';
import { DashboardTabs } from '../../components/dashboard/DashboardTabs.jsx';
import { api, apiMessage } from '../../services/api.js';
import { formatDate, humanize } from '../../utils/dashboard.js';
import { ResponsiveTable } from './MemberDashboardPage.jsx';

const emptyEditValues = { fullName: '', city: '', state: '', businessName: '', status: 'active', reason: '' };

export function AdminUserDetailPage() {
  const { id } = useParams(); const navigate=useNavigate(); const queryClient=useQueryClient(); const [active, setActive] = useState('account'); const [removeReason,setRemoveReason]=useState('');
  const detail = useQuery({ queryKey: ['admin-user', id], queryFn: async () => (await api.get(`/dashboard/admin/users/${id}`)).data.data });
  const editForm=useForm({defaultValues:emptyEditValues});
  useEffect(()=>{if(detail.data)editForm.reset(editValues(detail.data))},[detail.data,editForm]);
  const update=useMutation({mutationFn:(values)=>api.patch(`/dashboard/admin/users/${id}`,values),onSuccess:()=>Promise.all([queryClient.invalidateQueries({queryKey:['admin-user',id]}),queryClient.invalidateQueries({queryKey:['admin-users']}),queryClient.invalidateQueries({queryKey:['dashboard','admin']})])});
  const remove=useMutation({mutationFn:()=>api.delete(`/dashboard/admin/users/${id}`,{data:{reason:removeReason}}),onSuccess:()=>{queryClient.removeQueries({queryKey:['admin-user',id]});queryClient.invalidateQueries({queryKey:['admin-users']});queryClient.invalidateQueries({queryKey:['dashboard','admin']});navigate(`/admin/dashboard?section=${accountType(detail.data)==='contractor'?'contractors':'customers'}`,{replace:true})}});
  if (detail.isLoading) return <div className="shell route-loading">Loading user details…</div>;
  if (detail.isError) return <div className="shell route-loading"><h1>User unavailable</h1><p>{apiMessage(detail.error)}</p></div>;
  const { user, profile, metrics, referredUsers, loanReferrals, loginActivity } = detail.data; const type=accountType(detail.data); const directory=type==='contractor'?'contractors':'customers';
  const tabs = [{ id: 'account', label: 'Full details', icon: UserRound }, { id: 'manage', label: 'Manage account', icon: Pencil }, { id: 'registrations', label: 'Registrations', icon: Users, count: referredUsers.length }, { id: 'referrals', label: 'Service referrals', icon: FileText, count: loanReferrals.length }, { id: 'security', label: 'Login activity', icon: ShieldCheck, count: loginActivity.length }];
  function confirmRemoval(){if(removeReason.trim().length<3)return;if(window.confirm(`Remove ${user.fullName}'s portal access? Their applications, referrals, and audit history will be preserved.`))remove.mutate()}
  return <DashboardShell role="admin" title={user.fullName}><Link className="inline-link" to={`/admin/dashboard?section=${directory}`}>← Back to {directory}</Link><section className="dashboard-welcome"><div><span className="eyebrow">{type} details</span><h1>{user.fullName}</h1><p>{user.email||'No email'} · {user.mobile} · {humanize(user.status)}</p></div>{user.referralCode && <div className="referral-code-card"><span>Referral code</span><strong>{user.referralCode}</strong><Link to={`/admin/referrals/${user.referralCode}`}>Open code details</Link></div>}</section><section className="metric-grid"><Metric label="Successful logins" value={metrics.successfulLogins}/><Metric label="Last login" value={formatDate(user.lastLoginAt)}/><Metric label="Users referred" value={metrics.referredUsers}/><Metric label="Service referrals" value={metrics.loanReferrals}/></section><DashboardTabs tabs={tabs} active={active} onChange={setActive} label="User detail sections"/>
    {active === 'account' && <section className="dashboard-card dashboard-section tab-panel" role="tabpanel"><div className="card-heading"><div><span className="eyebrow">Registered information</span><h2>Account and profile details</h2><p>Login identifiers and user-owned activity are displayed read-only.</p></div><UserRound/></div><dl className="detail-list admin-account-details"><Detail label="Account type" value={humanize(type)}/><Detail label={`${humanize(type)} ID`} value={profile?.contractorId||profile?.customerId||'—'}/><Detail label="Full name" value={user.fullName}/><Detail label="Business name" value={profile?.businessName||'—'}/><Detail label="Email" value={user.email||'—'}/><Detail label="Phone" value={user.mobile}/><Detail label="City" value={profile?.city||'—'}/><Detail label="State" value={profile?.state||'—'}/><Detail label="Account status" value={humanize(user.status)}/><Detail label="Onboarding status" value={profile?.onboardingStatus?humanize(profile.onboardingStatus):'—'}/><Detail label="Referral code" value={user.referralCode||'—'}/><Detail label="Referred by" value={user.referredBy?.fullName||'Direct registration'}/><Detail label="Code used" value={user.referredByCode||'—'}/><Detail label="Registered" value={formatDate(user.createdAt)}/><Detail label="Email verified" value={formatDate(user.emailVerifiedAt)}/><Detail label="Mobile verified" value={formatDate(user.mobileVerifiedAt)}/><Detail label="First login" value={formatDate(user.firstLoginAt)}/><Detail label="Last login" value={formatDate(user.lastLoginAt)}/></dl></section>}
    {active === 'manage' && <div className="dashboard-columns tab-panel user-management-grid" role="tabpanel"><section className="dashboard-card dashboard-section"><div className="card-heading"><div><span className="eyebrow">Limited profile correction</span><h2>Edit allowed fields</h2><p>Email, mobile, referral code, applications, service referrals, and login history cannot be edited here.</p></div><Pencil/></div><form className="dashboard-form" onSubmit={editForm.handleSubmit((values)=>update.mutate(values))}><div className="form-grid"><Field label="Full name" register={editForm.register('fullName',{required:'Enter the full name',minLength:{value:2,message:'Enter at least 2 characters'}})} error={editForm.formState.errors.fullName}/>{type==='contractor'&&<Field label="Business name" register={editForm.register('businessName')}/>}<Field label="City" register={editForm.register('city')}/><Field label="State" register={editForm.register('state')}/><label>Portal access<select {...editForm.register('status')}><option value="active">Active</option><option value="suspended">Suspended</option></select></label></div><label>Reason for change<textarea rows="3" {...editForm.register('reason',{required:'Enter a reason for this administrative change',minLength:{value:3,message:'Enter at least 3 characters'}})}/>{editForm.formState.errors.reason&&<small className="field-error" role="alert">{editForm.formState.errors.reason.message}</small>}</label>{update.isError&&<p className="form-error">{apiMessage(update.error)}</p>}{update.isSuccess&&<p className="form-success">Account changes saved and recorded in the audit log.</p>}<button className="button button-gold" disabled={update.isPending}><Save size={17}/>{update.isPending?'Saving…':'Save allowed changes'}</button></form></section><section className="dashboard-card dashboard-section danger-zone"><div className="card-heading"><div><span className="eyebrow">Account removal</span><h2>Remove portal access</h2></div><Trash2/></div><p>This blocks sign-in and removes the person from admin directories. Financial applications, referrals, documents, and audit history remain preserved and cannot be edited through this action.</p><label>Required removal reason<textarea rows="4" value={removeReason} onChange={(event)=>setRemoveReason(event.target.value)} placeholder="Why is this account being removed?"/></label>{remove.isError&&<p className="form-error">{apiMessage(remove.error)}</p>}<button type="button" className="button danger-button" disabled={remove.isPending||removeReason.trim().length<3} onClick={confirmRemoval}><Trash2 size={17}/>{remove.isPending?'Removing access…':'Remove account access'}</button></section></div>}
    {active === 'registrations' && <section className="dashboard-card dashboard-section tab-panel" role="tabpanel"><h2>Users registered through this code</h2><ResponsiveTable columns={['Name', 'Role', 'Email', 'Phone', 'Registered', 'Action']} rows={referredUsers.map((item) => [item.fullName, item.roles?.map((role) => role.name).join(', '), item.email || '—', item.mobile, formatDate(item.createdAt), <Link className="table-link" key={item._id} to={`/admin/users/${item._id}`}>More details</Link>])} empty="No users registered through this code."/></section>}
    {active === 'referrals' && <section className="dashboard-card dashboard-section tab-panel" role="tabpanel"><div className="card-heading"><div><h2>Service referrals submitted</h2><p>These records belong to the user and remain read-only here.</p></div><FileText/></div><ResponsiveTable columns={['ID', 'Applicant', 'Service', 'Submitted', 'Status']} rows={loanReferrals.map((item) => [item.referralId, item.applicant.fullName, item.service?.name || '—', formatDate(item.createdAt), humanize(item.status)])} empty="No service referrals submitted."/></section>}
    {active === 'security' && <section className="dashboard-card dashboard-section tab-panel" role="tabpanel"><h2>Successful login history</h2><ResponsiveTable columns={['Date', 'Role', 'IP', 'Device']} rows={loginActivity.map((item) => [formatDate(item.loginAt), humanize(item.role), item.ip || '—', item.userAgent || 'Unknown'])} empty="No login activity recorded."/></section>}
  </DashboardShell>;
}

function accountType(data){return data?.user?.roles?.some((role)=>role.slug==='contractor')?'contractor':'customer'}
function editValues(data){return {fullName:data.user.fullName||'',city:data.profile?.city||'',state:data.profile?.state||'',businessName:data.profile?.businessName||'',status:['active','suspended'].includes(data.user.status)?data.user.status:'suspended',reason:''}}
function Detail({label,value}){return <div><dt>{label}</dt><dd>{value}</dd></div>}
function Metric({ label, value }) { return <article className="metric-card compact"><span>{label}</span><strong>{value}</strong></article>; }
function Field({label,register,error}){return <label>{label}<input aria-invalid={Boolean(error)} {...register}/>{error&&<small className="field-error" role="alert">{error.message}</small>}</label>}
