import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { FileCheck2, ListFilter, Search, Workflow } from 'lucide-react';
import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { DashboardShell } from '../../components/dashboard/DashboardShell.jsx';
import { DashboardTabs, Pagination } from '../../components/dashboard/DashboardTabs.jsx';
import { api, apiMessage } from '../../services/api.js';
import { formatDate, humanize } from '../../utils/dashboard.js';
import { ResponsiveTable } from './MemberDashboardPage.jsx';

const statuses = ['submitted', 'new', 'contacted', 'documents_pending', 'documents_received', 'under_internal_review', 'additional_information_required', 'submitted_to_provider', 'under_provider_review', 'approved', 'rejected', 'disbursed_or_policy_issued', 'closed', 'cancelled'];
const pageSize = 25;

export function AdminApplicationsPage() {
  const [active, setActive] = useState('list'); const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [selected, setSelected] = useState(null); const [page, setPage] = useState(1);
  const applications = useQuery({ queryKey: ['admin-applications', search, status, page], enabled: active === 'list', queryFn: async () => (await api.get('/dashboard/admin/applications', { params: { q: search, status, page, limit: pageSize } })).data });
  const tabs = [{ id: 'list', label: 'All applications', icon: ListFilter, count: applications.data?.meta?.total }, { id: 'manage', label: 'Manage selected', icon: Workflow, count: selected ? 1 : 0 }];
  function openApplication(id) { setSelected(id); setActive('manage'); }
  function closeApplication() { setSelected(null); setActive('list'); }
  return <DashboardShell role="admin" title="Applications"><section className="dashboard-welcome"><div><span className="eyebrow">Application operations</span><h1>Manage live public applications.</h1><p>Completed submissions from the public Apply page appear here automatically. Saved drafts stay private until submitted.</p></div><FileCheck2/></section><DashboardTabs tabs={tabs} active={active} onChange={setActive} label="Application management sections"/>
    {active === 'list' && <section className="dashboard-card dashboard-section tab-panel" role="tabpanel"><div className="dashboard-filters"><label><Search/><input value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} placeholder="Application ID, lead ID, name, mobile"/></label><select aria-label="Filter applications by status" value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }}><option value="">All statuses</option>{statuses.map((item) => <option value={item} key={item}>{humanize(item)}</option>)}</select></div>{applications.isLoading ? <div className="empty-state">Loading applications…</div> : applications.isError ? <p className="form-error">{apiMessage(applications.error)}</p> : <><ResponsiveTable columns={['Application', 'Applicant', 'Service', 'Requested', 'Submitted', 'Status', 'Action']} rows={(applications.data?.data || []).map((item) => [item.applicationId, <span key="person">{item.personal?.fullName}<small>{item.personal?.mobile}</small></span>, item.service?.name || '—', item.financial?.requestedAmount ? new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(item.financial.requestedAmount) : '—', formatDate(item.submittedAt), humanize(item.status), <button key="open" className="table-link text-button" onClick={() => openApplication(item._id)}>Manage</button>])} empty="No submitted applications match the filters."/><Pagination page={page} pages={applications.data?.meta?.pages} total={applications.data?.meta?.total} onChange={setPage} label="applications"/></>}</section>}
    {active === 'manage' && (selected ? <ApplicationDetail id={selected} onClose={closeApplication}/> : <section className="dashboard-card dashboard-section tab-panel empty-state" role="tabpanel"><FileCheck2/><h2>No application selected</h2><p>Open the “All applications” tab and choose Manage beside an application.</p><button className="button button-gold" type="button" onClick={() => setActive('list')}>Choose an application</button></section>)}
  </DashboardShell>;
}

function ApplicationDetail({ id, onClose }) {
  const queryClient = useQueryClient(); const detail = useQuery({ queryKey: ['admin-application', id], queryFn: async () => (await api.get(`/dashboard/admin/applications/${id}`)).data.data });
  const form = useForm({ defaultValues: { status: 'contacted', publicNote: '', internalNote: '', reason: '' } });
  const update = useMutation({ mutationFn: (values) => api.patch(`/dashboard/admin/applications/${id}/status`, values), onSuccess: () => { form.reset(); queryClient.invalidateQueries({ queryKey: ['admin-application', id] }); queryClient.invalidateQueries({ queryKey: ['admin-applications'] }); } });
  if (detail.isLoading) return <section className="dashboard-card dashboard-section tab-panel">Loading application detail…</section>;
  if (detail.isError) return <section className="dashboard-card dashboard-section tab-panel"><p className="form-error">{apiMessage(detail.error)}</p></section>;
  const data = detail.data; const application = data.application;
  return <section className="dashboard-card dashboard-section application-admin-detail tab-panel" role="tabpanel"><div className="card-heading"><div><span className="eyebrow">{application.applicationId}</span><h2>{application.personal?.fullName}</h2></div><button className="button button-outline" onClick={onClose}>Back to applications</button></div><dl className="detail-list"><div><dt>Mobile</dt><dd>{application.personal?.mobile}</dd></div><div><dt>Email</dt><dd>{application.personal?.email}</dd></div><div><dt>Location</dt><dd>{[application.personal?.city, application.personal?.state, application.personal?.country, application.personal?.pinCode].filter(Boolean).join(', ')}</dd></div><div><dt>Service</dt><dd>{application.service?.name}</dd></div><div><dt>Status</dt><dd>{humanize(application.status)}</dd></div><div><dt>Employment</dt><dd>{humanize(application.financial?.employmentType)}</dd></div><div><dt>Requested amount</dt><dd>{formatCurrency(application.financial?.requestedAmount)}</dd></div><div><dt>Referral code</dt><dd>{application.referralCode || 'Direct'}</dd></div></dl><div className="dashboard-columns"><article><h3>Status history</h3><ol className="admin-timeline">{data.history.map((item) => <li key={item._id}><strong>{humanize(item.newStatus)}</strong><p>{item.publicNote}</p><small>{formatDate(item.createdAt)}</small></li>)}</ol></article><form className="dashboard-form" onSubmit={form.handleSubmit((values) => update.mutate(values))}><h3>Publish status update</h3><label>New status<select {...form.register('status', { required: true })}>{statuses.map((item) => <option value={item} key={item}>{humanize(item)}</option>)}</select></label><label>Customer-visible note<textarea rows="3" {...form.register('publicNote', { required: true, minLength: 5 })}/></label><label>Internal note<textarea rows="2" {...form.register('internalNote')}/></label><Field label="Reason for change" register={form.register('reason', { required: true, minLength: 3 })}/><button className="button button-gold" disabled={update.isPending}>{update.isPending ? 'Updating…' : 'Update application status'}</button>{update.isError && <p className="form-error">{apiMessage(update.error)}</p>}</form></div></section>;
}
function formatCurrency(value) { return Number(value) > 0 ? new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value) : '—'; }
function Field({ label, register }) { return <label>{label}<input {...register}/></label>; }
