export const permissions = [
  ['customers.view', 'View authorized customer records'], ['customers.edit', 'Edit authorized customer records'], ['customers.suspend', 'Suspend customer accounts'],
  ['contractors.view', 'View contractor records'], ['contractors.approve', 'Approve or reject contractors'], ['contractors.suspend', 'Suspend contractor accounts'],
  ['applications.view', 'View authorized applications'], ['applications.create', 'Create applications'], ['applications.assign', 'Assign applications'], ['applications.status.update', 'Change application status'],
  ['documents.view', 'View authorized documents'], ['documents.verify', 'Verify documents'], ['documents.reject', 'Reject documents'],
  ['subscriptions.view', 'View subscriptions'], ['subscriptions.manage', 'Manage subscriptions'], ['payments.view', 'View payments'], ['payments.manage', 'Manage payments and refunds'],
  ['commissions.view', 'View commissions'], ['commissions.approve', 'Approve commissions'], ['commissions.pay', 'Record commission payments'],
  ['support.view', 'View support tickets'], ['support.manage', 'Manage support tickets'], ['content.manage', 'Manage CMS content'], ['content.publish', 'Publish CMS content'],
  ['reports.view', 'View reports'], ['reports.export', 'Export reports'], ['settings.manage', 'Manage system settings'], ['roles.manage', 'Manage roles and permissions'], ['audit.view', 'View immutable audit records'],
];

export const roleDefinitions = {
  'super-admin': permissions.map(([key]) => key),
  admin: permissions.map(([key]) => key).filter((key) => key !== 'roles.manage'),
  'operations-manager': ['customers.view', 'customers.edit', 'contractors.view', 'contractors.approve', 'applications.view', 'applications.create', 'applications.assign', 'applications.status.update', 'documents.view', 'documents.verify', 'documents.reject', 'support.view', 'reports.view', 'reports.export'],
  'application-manager': ['customers.view', 'contractors.view', 'applications.view', 'applications.create', 'applications.assign', 'applications.status.update', 'documents.view', 'documents.verify', 'documents.reject', 'reports.view'],
  'finance-manager': ['customers.view', 'contractors.view', 'applications.view', 'subscriptions.view', 'subscriptions.manage', 'payments.view', 'payments.manage', 'commissions.view', 'commissions.approve', 'commissions.pay', 'reports.view', 'reports.export'],
  'support-agent': ['customers.view', 'contractors.view', 'applications.view', 'support.view', 'support.manage'],
  'content-manager': ['content.manage', 'content.publish'],
  contractor: ['customers.view', 'applications.view', 'applications.create', 'documents.view', 'subscriptions.view', 'payments.view', 'commissions.view', 'support.view', 'reports.view'],
  customer: ['applications.view', 'applications.create', 'documents.view', 'subscriptions.view', 'payments.view', 'support.view'],
};

const commonProcess = ['Share your requirement', 'Submit accurate information and requested documents', 'VFS Groups reviews the application for completeness', 'The application may be submitted to a relevant provider', 'Track progress and respond to additional requests'];
const commonEligibility = ['Eligibility depends on applicant profile, documentation, requested amount, and the policies of the relevant lender or provider', 'Rates, tenure, charges, and approval are determined by the relevant institution'];
const commonFaqs = [{ question: 'Is approval guaranteed?', answer: 'No. Approval, pricing, tenure, and disbursement depend on the relevant lender or provider and the applicant profile.' }, { question: 'Can VFS Groups help with documents?', answer: 'VFS Groups can guide applicants on commonly requested documentation and help track completeness.' }];

export const services = [
  { name: 'Home Loan', slug: 'home-loan', category: 'Home & Property Finance', shortDescription: 'Application assistance for new and resale residential property purchases.', overview: 'Explore home finance options for an eligible residential purchase with documentation and application support.', features: ['New or resale property use cases', 'Applicant and co-applicant assessment', 'Application tracking'], suitableFor: ['Salaried applicants', 'Self-employed applicants', 'Eligible co-applicants'], useCases: ['New residential property purchase', 'Resale property purchase'], documents: ['Identity and address proof', 'Income records and bank statements', 'Property documents'], relatedSlugs: ['construction-loan', 'balance-transfer-top-up'] },
  { name: 'Construction Loan', slug: 'construction-loan', category: 'Home & Property Finance', shortDescription: 'Funding assistance for construction on eligible owned land.', overview: 'Construction finance commonly considers land title, approved plans, estimates, income, and stage-wise progress.', features: ['Stage-wise funding considerations', 'Plan and estimate review', 'Documentation guidance'], suitableFor: ['Owners of eligible land', 'Applicants with approved construction plans'], useCases: ['Residential construction on owned land'], documents: ['Land ownership documents', 'Approved building plan', 'Construction estimate', 'Income records'], relatedSlugs: ['home-loan', 'project-construction-loan'] },
  { name: 'Balance Transfer & Top-Up', slug: 'balance-transfer-top-up', category: 'Home & Property Finance', shortDescription: 'Review an existing eligible loan for transfer and possible top-up.', overview: 'Compare the outstanding balance, current terms, repayment history, remaining tenure, and potential transfer costs.', features: ['Existing loan review', 'Illustrative savings comparison', 'Top-up requirement capture'], suitableFor: ['Borrowers with an existing eligible loan'], useCases: ['Transfer an existing loan', 'Request additional eligible funding'], documents: ['Existing sanction letter', 'Repayment statement', 'Income and bank records'], relatedSlugs: ['home-loan', 'mortgage-loan'] },
  { name: 'Overdraft Facility', slug: 'overdraft-facility', category: 'Home & Property Finance', shortDescription: 'Explore flexible credit facilities for eligible salaried or business needs.', overview: 'An overdraft may provide a sanctioned limit with interest generally linked to utilized funds, subject to provider rules.', features: ['Flexible utilization concept', 'Secured or eligible unsecured possibilities', 'Renewal considerations'], suitableFor: ['Eligible businesses', 'Eligible salaried applicants', 'Property owners where collateral is required'], useCases: ['Working capital', 'Short-term cash-flow needs'], documents: ['Income or business records', 'Bank statements', 'Collateral records where applicable'], relatedSlugs: ['business-loan', 'mortgage-loan'] },
  { name: 'Mortgage Loan', slug: 'mortgage-loan', category: 'Home & Property Finance', shortDescription: 'Loan assistance against eligible residential, commercial, or industrial property.', overview: 'Mortgage applications generally involve ownership, legal, technical, valuation, income, and repayment assessment.', features: ['Property-backed use cases', 'Valuation and legal review considerations', 'Personal or business purposes'], suitableFor: ['Owners of eligible property'], useCases: ['Business funding', 'Eligible personal funding', 'Debt consolidation'], documents: ['Property title chain', 'Identity and income records', 'Bank statements'], relatedSlugs: ['land-mortgage-loan', 'industrial-mortgage-loan'] },
  { name: 'Business Loan', slug: 'business-loan', category: 'Business & Industrial Finance', shortDescription: 'Funding assistance for eligible working-capital and business growth needs.', overview: 'Business loan assessment can consider business type, vintage, turnover, cash flow, tax records, and existing obligations.', features: ['Secured and unsecured possibilities', 'Business cash-flow assessment', 'Growth requirement capture'], suitableFor: ['Proprietorships', 'Partnerships', 'Eligible companies and professionals'], useCases: ['Working capital', 'Inventory', 'Expansion', 'Machinery'], documents: ['Business registration', 'GST and tax records', 'Bank statements', 'Financial statements'], relatedSlugs: ['overdraft-facility', 'industrial-purchase-loan'] },
  { name: 'Industrial Mortgage Loan', slug: 'industrial-mortgage-loan', category: 'Business & Industrial Finance', shortDescription: 'Property-backed funding assistance for eligible industrial requirements.', overview: 'Industrial mortgage review includes property, business, financial, legal, and repayment information.', features: ['Industrial property assessment', 'Business financial review', 'Multiple eligible end uses'], suitableFor: ['Owners of eligible industrial property'], useCases: ['Working capital', 'Expansion', 'Equipment', 'Operational requirements'], documents: ['Industrial property documents', 'Registration and GST records', 'Financial statements and tax returns'], relatedSlugs: ['mortgage-loan', 'industrial-purchase-loan'] },
  { name: 'Industrial Purchase Loan', slug: 'industrial-purchase-loan', category: 'Business & Industrial Finance', shortDescription: 'Purchase finance assistance for eligible industrial property.', overview: 'Applications can consider property value, applicant contribution, business performance, valuation, and legal/technical verification.', features: ['Industrial land or unit use cases', 'Legal and technical review considerations', 'Business profile assessment'], suitableFor: ['Eligible businesses purchasing industrial property'], useCases: ['Factory purchase', 'Warehouse purchase', 'Commercial or industrial unit purchase'], documents: ['Target property documents', 'Business and financial records', 'Promoter contribution evidence'], relatedSlugs: ['industrial-mortgage-loan', 'business-loan'] },
  { name: 'Land Mortgage Loan', slug: 'land-mortgage-loan', category: 'Home & Property Finance', shortDescription: 'Funding assistance against land types accepted by relevant lenders.', overview: 'Eligibility varies significantly by land category, approved use, ownership, location, valuation, and lender policy.', features: ['Land-category assessment', 'Ownership and encumbrance review', 'Purpose capture'], suitableFor: ['Owners of land types accepted under provider policy'], useCases: ['Eligible personal or business funding'], documents: ['Ownership and land records', 'Encumbrance information', 'Income or business records'], relatedSlugs: ['mortgage-loan', 'industrial-mortgage-loan'] },
  { name: 'Project Loan', slug: 'project-loan', category: 'Project Finance', shortDescription: 'Structured application support for eligible business and development projects.', overview: 'Project finance review can include project cost, promoter contribution, approvals, revenue assumptions, risk, and detailed projections.', features: ['Project report review', 'Funding and contribution mapping', 'Approval and risk checklist'], suitableFor: ['Eligible business, industrial, infrastructure, or real-estate projects'], useCases: ['New projects', 'Project expansion'], documents: ['Detailed project report', 'Approvals and licences', 'Financial projections', 'Promoter information'], relatedSlugs: ['project-construction-loan', 'business-loan'] },
  { name: 'Project Construction Loan', slug: 'project-construction-loan', category: 'Project Finance', shortDescription: 'Stage-based finance assistance for eligible project construction.', overview: 'Review commonly covers plans, approvals, contractors, estimates, timelines, projected cash flow, and stage-wise funding needs.', features: ['Construction milestone mapping', 'Cost and timeline review', 'Stage-wise funding considerations'], suitableFor: ['Eligible project developers and businesses'], useCases: ['Project development and construction'], documents: ['Plans and approvals', 'Contractor and cost records', 'Timeline and revenue projections'], relatedSlugs: ['project-loan', 'construction-loan'] },
  { name: 'Personal Loan', slug: 'personal-loan', category: 'Personal Finance', shortDescription: 'Application assistance for eligible personal funding requirements.', overview: 'Personal loan assessment generally considers employment or business income, credit profile, obligations, requested amount, and tenure.', features: ['Salaried and self-employed profiles', 'Income and obligation review', 'Application tracking'], suitableFor: ['Eligible salaried applicants', 'Eligible self-employed applicants'], useCases: ['Eligible personal expenses'], documents: ['Identity and address proof', 'Income proof', 'Bank statements'], relatedSlugs: ['home-loan', 'business-loan'] },
  { name: 'Vehicle Insurance', slug: 'vehicle-insurance', category: 'Insurance', shortDescription: 'Assistance exploring eligible motor insurance and renewal options.', overview: 'Cover, exclusions, premium, add-ons, and claims are governed by the selected insurer and official policy wording.', features: ['Car, bike, and commercial vehicle assistance', 'Third-party and comprehensive options', 'Renewal and claim-support guidance'], suitableFor: ['Eligible vehicle owners'], useCases: ['New cover', 'Renewal', 'Add-on review'], documents: ['Vehicle registration', 'Existing policy for renewal', 'Identity details'], relatedSlugs: ['life-insurance'] },
  { name: 'Life Insurance', slug: 'life-insurance', category: 'Insurance', shortDescription: 'Guidance while exploring eligible life-protection and long-term plans.', overview: 'Benefits, exclusions, premiums, returns, and claims depend entirely on official policy terms and insurer assessment.', features: ['Protection-plan guidance', 'Nominee and premium-frequency capture', 'Claim-support process guidance'], suitableFor: ['Applicants meeting insurer eligibility and underwriting rules'], useCases: ['Term protection', 'Retirement or child planning exploration', 'Eligible savings-linked plans'], documents: ['Identity and age proof', 'Income information where required', 'Medical information when requested'], relatedSlugs: ['vehicle-insurance'] },
].map((service, index) => ({ ...service, eligibility: commonEligibility, process: commonProcess, considerations: ['Read all applicable provider terms, charges, exclusions, and conditions before proceeding'], faqs: commonFaqs, status: 'published', sortOrder: index + 1, seo: { title: `${service.name} Assistance | VFS Groups`, description: service.shortDescription } }));
